# Generated by Django 5.0 on 2023-12-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=100)),
                ('Emp_phn', models.IntegerField()),
                ('Emp_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
