# Generated by Django 5.0 on 2023-12-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_emp_emp_email_alter_emp_emp_phn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='Emp_phn',
        ),
        migrations.AddField(
            model_name='emp',
            name='Emp_message',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp',
            name='Emp_email',
            field=models.EmailField(max_length=50),
        ),
    ]
