# Generated by Django 5.0 on 2023-12-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_emp_emp_phn_emp_emp_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='Emp_message',
            new_name='Emp_password',
        ),
    ]
