# Generated by Django 5.0 on 2023-12-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_emp_emp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='Emp_password',
            field=models.CharField(max_length=100),
        ),
    ]
